MAX_CURRENT_PER_LED = 0.045
LINE_OVERAGE_BUFFER_PERCENT = 0.05
MAX_CONTROLLERS_PER_JUNCTION_BOX = 4
MAX_CHANNELS_PER_CONTROLLER = 8
EXPECTED_TOTAL_CONTROLLER_COUNT = 49
PANEL_TYPE_LIT = 'lit'
PANEL_TYPE_SOLID = 'solid'