#!/bin/bash
set -e

changed_java_files=$(git diff --cached --name-only --diff-filter=ACMR | grep ".*java$" || true)
if [[ -n "$changed_java_files" ]]
then
    if ! mvn spotless:check
    then
        echo "An error occurred, aborting commit!" >&2
        exit 1
    fi
else
    echo "No Java files changes found."
fi
