# Resolume OSC Sync Configuration
# This file maps OSC messages from TE/Chromatik to Resolume Arena/Avenue

# Network configuration for Resolume machine
resolume:
  network:
    ip: "127.0.0.1"
    port: 7000

  # OSC message mappings: TE OSC Path → Resolume OSC Path
  mappings:
    # Tempo and beat sync
    "/lx/tempo/beat": "/test/tempo/resync"
