package titanicsend.pattern.glengine;

public enum ShaderConfigOpcode {
  AUTO,
  SET_VALUE,
  SET_RANGE,
  SET_LABEL,
  SET_EXPONENT,
  SET_NORMALIZATION_CURVE,
  SET_TEXTURE,
  DISABLE,
  SET_TRANSLATE_MODE_NORMAL,
  SET_TRANSLATE_MODE_DRIFT,
  SET_CLASS_NAME,
  SET_LX_CATEGORY,
  ADD_LX_PARAMETER
}
