##name: Maven Checks
on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev
jobs:
  maven-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      # Note: ensuring maven is updated, so newer properties like 'multiModuleProjectRoot' work as expected.
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.9
      - name: Verify Maven Compilation Success
        run: mvn compile
      - name: Check Code Style
        run: mvn spotless:check
