##name: Maven Checks
on:
  pull_request:
    branches:
      - main
      - dev
      - look/remove-model-debug-effects
  push:
    branches:
      - main
      - dev
      - look/remove-model-debug-effects
jobs:
  maven-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Verify Maven Compilation Success
        run: mvn compile
      - name: Check Code Style
        run: mvn spotless:check
